### ISSUE TITLE
Installed plugins are not recognized

### ISSUE THREAD

**Issue by argyrodagdileli** [rundeck/welcome-project-community#28]
Hi,

I've been playing around with the project to familiarize my self with Rundeck, but I've been having issues installing plugins.
Namely - when I install a plugin I get the message that it was installed successfully but it doesn't appear under the installed plugins and I cannot use it. 
When I go back to the plugins available for installation I can see the plugin as it was never installed.

Steps to reproduce

1. Navigate to `Plugins -> Find Plugins`
2. Search for a plugin e.g. `PagerDuty Notification` 
3.  Click `Install` 
4. Wait for the installation to complete.
5. Verify that the `Uninstall` option appears.
![image](https://user-images.githubusercontent.com/25536196/186876931-d85fd747-b1d6-4d2f-ba81-371868c3c915.png)
6. Refresh the page
7. Verify that the `Install` option appears again under the plugin 
![image](https://user-images.githubusercontent.com/25536196/186877384-ad2e1436-ce0f-40f2-a4b2-e429516f8a34.png)

What is weird is that the plugin `.jar` file appears under the `/home/rundeck/libext` folder

```
docker exec rundeck ls /home/rundeck/libext
<output omitted>
pagerduty-notification.jar
<output omitted>
```

Any ideas? Am I missing something?

**Comment by argyrodagdileli** [comment]
Okay it looks like during startup the plugin directory watcher fails to start - any ideas?

```
Failed to start plugin dir watcher
java.io.IOException: Function not implemented
        at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at com.dtolabs.rundeck.core.plugins.WatchingPluginDirProvider.lambda$startFolderWatch$0(WatchingPluginDirProvider.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
